In [1]:
import tensorflow as tf

tensorflow使用细节
# `tf.newaxis`使用

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a[:,tf.newaxis]

array([[1],
       [2],
       [3]])

In [6]:
a[...,tf.newaxis]

array([[1],
       [2],
       [3]])

# `TensorSliceDataset.shuffle`

2019年10月21日：目前`buffer_size`参数影响不明，但是一定要有

In [13]:
a = np.array(range(100))[:,tf.newaxis]
b = np.array(range(0,200,2))[:,tf.newaxis]

t = tf.data.Dataset.from_tensor_slices((a,b))
a.shape,b.shape

((100, 1), (100, 1))

In [18]:
t2 = t.shuffle(100)
t2,str(dir(t2))

(<ShuffleDataset shapes: ((1,), (1,)), types: (tf.int32, tf.int32)>,
 "['_GeneratorState', '__abstractmethods__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_add_variable_with_custom_getter', '_apply_options', '_as_serialized_graph', '_buffer_size', '_checkpoint_dependencies', '_component_metadata', '_consumers', '_deferred_dependencies', '_flat_shapes', '_flat_structure', '_flat_types', '_from_components', '_functions', '_gather_saveables_for_checkpoint', '_graph', '_graph_attr', '_handle_deferred_dependencies', '_has_captured_ref', '_input_dataset', '_inputs', '_is_graph_tensor', '_list_extra

In [19]:
t3 = t2.batch(6)
t3,str(dir(t3))

(<BatchDataset shapes: ((None, 1), (None, 1)), types: (tf.int32, tf.int32)>,
 "['_GeneratorState', '__abstractmethods__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_add_variable_with_custom_getter', '_apply_options', '_as_serialized_graph', '_batch_size', '_checkpoint_dependencies', '_component_metadata', '_consumers', '_deferred_dependencies', '_drop_remainder', '_flat_shapes', '_flat_structure', '_flat_types', '_from_components', '_functions', '_gather_saveables_for_checkpoint', '_graph', '_graph_attr', '_handle_deferred_dependencies', '_has_captured_ref', '_input_dataset', '_inputs', '_is_g

In [20]:
for i,tensor in enumerate(t3):
    print(i,' -> :\n',tensor)

0  -> :
 (<tf.Tensor: id=104, shape=(6, 1), dtype=int32, numpy=
array([[97],
       [69],
       [ 1],
       [75],
       [82],
       [92]])>, <tf.Tensor: id=105, shape=(6, 1), dtype=int32, numpy=
array([[194],
       [138],
       [  2],
       [150],
       [164],
       [184]])>)
1  -> :
 (<tf.Tensor: id=106, shape=(6, 1), dtype=int32, numpy=
array([[71],
       [16],
       [81],
       [11],
       [10],
       [31]])>, <tf.Tensor: id=107, shape=(6, 1), dtype=int32, numpy=
array([[142],
       [ 32],
       [162],
       [ 22],
       [ 20],
       [ 62]])>)
2  -> :
 (<tf.Tensor: id=108, shape=(6, 1), dtype=int32, numpy=
array([[14],
       [95],
       [21],
       [17],
       [76],
       [32]])>, <tf.Tensor: id=109, shape=(6, 1), dtype=int32, numpy=
array([[ 28],
       [190],
       [ 42],
       [ 34],
       [152],
       [ 64]])>)
3  -> :
 (<tf.Tensor: id=110, shape=(6, 1), dtype=int32, numpy=
array([[39],
       [93],
       [53],
       [46],
       [13],
       [20]])